pop_gen_gammaridae_v0 : pop_gen_gammaridae_v0.cpp include/classes.h include/procedures.h
	g++ -Wall -g -o pop_gen_gammaridae_v0 pop_gen_gammaridae_v0.cpp -lgsl -lgslcblas -lm -static
	
all:	pop_gen_gammaridae_v0

clean:
	rm -f pop_gen_gammaridae_v0
